name: yaosulee_mobile
description: YaosuLee WebView App with video splash and VIP routing
publish_to: "none"
version: 1.0.7+4

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.8.0
  webview_flutter_android: ^3.16.0
  webview_flutter_wkwebview: ^3.12.0
  video_player: ^2.9.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/splash/intro.mp4

flutter_icons:
  android: true
  ios: true
  image_path: assets/icons/app_icon.png
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: assets/icons/app_icon.png


